apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-frontend-stage
  name: sample-frontend-stage
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    load-balancer-sample-frontend-stage: "true"
  sessionAffinity: None
  type: LoadBalancer
