apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-backend-stage
  name: sample-backend-stage
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    load-balancer-sample-backend-stage: "true"
  sessionAffinity: None
  type: ClusterIP
